export const Categories=[
    {
        _id:0,
        name:"Sports",
        value:'sports'
    },
    {
        _id:1,
        name:"Politics",
        value:'politics'
    },
    {
        _id:2,
        name:"Business",
        value:'business'
    },
    {
        _id:3,
        name:"Entertainment",
        value:'entertainment'
    },
    {
        _id:5,
        name:"Environment",
        value:'environment'
    },
    {
        _id:6,
        name:"Food",
        value:'food'
    }, 
    {
        _id:7,
        name:"Health",
        value:'health'
    },
    {
        _id:8,
        name:"Science",
        value:'science'
    },
    {
        _id:9,
        name:"Technology",
        value:'technology'
    },  
    {
        _id:10,
        name:"Top",
        value:'top'
    },
    {
        _id:11,
        name:"Tourism",
        value:'tourism'
    },  
    {
        _id:12,
        name:"World",
        value:'world'
    }, 
]