# Generated by Django 4.2.5 on 2023-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news_img',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
