# Generated by Django 4.2.5 on 2023-09-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_text_alter_news_img_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_img',
            name='img',
            field=models.ImageField(upload_to='images/news'),
        ),
    ]
