# Generated by Django 4.2.5 on 2023-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_img_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_img',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news_text',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_img',
            name='img',
            field=models.ImageField(upload_to='news_image'),
        ),
    ]
